// TODO: Add Firebase options, usually generated by `flutterfire configure`
// For example:
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web -_-',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         // return android;
//       case TargetPlatform.iOS:
//         // return ios;
//       case TargetPlatform.macOS:
//         // return macos;
//       case TargetPlatform.windows:
//         // throw UnsupportedError(
//         //   'DefaultFirebaseOptions have not been configured for windows -_-',
//         // );
//       case TargetPlatform.linux:
//         // throw UnsupportedError(
//         //   'DefaultFirebaseOptions have not been configured for linux -_-',
//         // );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//   // Add your platform specific FirebaseOptions here
// }
